language: go
go:
- 1.10.x
branches:
  only:
  - master
script:
- make zip
- go test -v ./...
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
  - octodns-linux-amd64.zip
  skip_cleanup: true
  on:
    tags: true
env:
  secure: tVZK/NEWNT4EC4/F+MGGl7p3bdhnly+iWvD05h1bYW5F4Mx6LyPAHCnozxKKC2da17JzFMQ6Fg8oBJ2YFLjx4lHFauZvRjEdKqdZZ2KyUTyUxbHECzCic1Hg8wqkZQWiFPqukSWAGaUxk5pTD5WZdYyhh7E1+mhYEVwKc2sc4T1u9xBlswxTL7xAuNud2vIkr83ulUYJGbwi8zK5Fn00hsksm9lxgIEByFerYBKkZwb/a2kHQlRVAcrPRtsQztiodZrHKHtXsH0a8J4026eOD1oOJLX4KTrtxhxcTf9Es14UkgzjzGKWPwtm9ADPnU6top2Hp2EYjxTAdbIIwQr0SdsnBrziqrV2ZYciy+bIZ1KFAEEoBll6BgRClHGMAMS20dUxnMStLHkxTNnN/JVQtjo8Y6TDvyG/j++m0uVaLgoL1GHDdDR/+wX0oWPJx+rb9TX4p2Cyy4RDJAD17eO1F0HxXA7zUlaqBedowv6PkkQgzB2PbgtdF3XIkEPDiJXbd4PbHCNIoYW/KTooGaGJubzAf2p1Lm2ywZyCe79XqqRxBTDk99hAcXgVaBLd6mkKqgEo8kechrVcZlniXMwJVzviYz/PzVT6Ky/fF94CFz5lQFxAW687bM1bOn3SsZfGPIJC0/Bo3fKAmYXuR6OAWedbnixa3mJeWv5D3glfJP4=
